ecomsite/Cart/urls.py
from django.urls import path
from .views import cart,addToCart,subtractQuantity,removeFromCart,increaseQuantity
urlpatterns = [
    path('',cart,name='cart'),
    path('addtocart/<int:product_id>',addToCart,name="addToCart"),
    path('subtractfromcart/<int:product_id>',subtractQuantity,name="subtractfromcart"),
    path('increasequantity/<int:cart_item_id>',increaseQuantity,name="increasequantity"),
    path('remove/<int:cart_item_id>',removeFromCart,name="removeFromCart"),
]

ecomsite/ecomsite/urls.py
from django.contrib import admin
from django.urls import path
from .views import home
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name="home"),
    path('store/',include('store.urls')),
    path('cart/',include('Cart.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomsite/store/urls.py
from django.urls import path
from .views import store,product_details,search
urlpatterns = [
    path('',store,name='store'),
    path('<slug:category_slug>',store,name="productByCategory"),
    path('<slug:category_slug>/<slug:product_slug>', product_details, name="product_details"),
    path('search/',search,name='search'),
]

ecomsite/Cart/models.py
from django.db import models
from store.models import Product,ProductVariation
# Create your models here.
class Cart(models.Model):
    cartId = models.CharField(max_length=200,blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cartId

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation = models.ManyToManyField(ProductVariation,blank=True)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return  self.quantity*self.product.price
    def __unicode__(self):
        return self.product

ecomsite/store/models.py
from django.db import models
from django.urls import reverse
from Category.models import Category
# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True,null=True)
    price = models.FloatField()
    stock = models.IntegerField()
    images = models.ImageField(upload_to='images/products')
    is_available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse("product_details",args=[self.category.slug,self.slug])

variationChoices = (
    ('Color','color'),
    ('Size','size')
)

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variationChoice='Color',is_active=True)
    def sizes(self):
        return super(VariationManager,self).filter(variationChoice='Size',is_active=True)
class ProductVariation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variationChoice = models.CharField(max_length=30,choices=variationChoices)
    variationValue = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    objects = VariationManager()
    class Meta:
        unique_together = ('product','variationChoice','variationValue')

    def __str__(self):
        return self.variationValue

ecomsite/Cart/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from store.models import Product,ProductVariation
from .models import Cart,CartItem
# Create your views here.
def _cartId(request):
    cart  = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def subtractQuantity(request,cart_item_id):
    cart = Cart.objects.get(cartId=_cartId(request))
    cartItem = CartItem.objects.get(id=cart_item_id,cart=cart)
    if cartItem.quantity>1:
        cartItem.quantity-=1
        cartItem.save()
    else:
        cartItem.delete()
    return redirect('cart')

def removeFromCart(request,cart_item_id):
    cart = Cart.objects.get(cartId=_cartId(request))
    cartItem = CartItem.objects.get(id=cart_item_id,cart=cart)
    cartItem.delete()
    return redirect('cart')


def cart(request,quantity=0,total=0,cartItems=None):
    try:
        cart = Cart.objects.get(cartId = _cartId(request))
        cartItems = CartItem.objects.filter(cart=cart,is_active=True)
        for cartitem in cartItems:
            total += cartitem.product.price*cartitem.quantity
            quantity += quantity+cartitem.quantity
        tax = (2*total)/100
        grand_total = total+tax
    except Exception as e:
        print(e)
    context = {
        'total':total,
        'cartItems':cartItems,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total,
    }
    return render(request,'cart.html',context)



def addToCart(request,product_id):
    product = Product.objects.get(id=product_id)
    product_variation = []
    for key in request.POST:
        value = request.POST[key]
        try:
            variation = ProductVariation.objects.get(product=product,variationChoice__iexact=key,variationValue__iexact=value)
            product_variation.append(variation)
        except:
            pass
    try:
        cart = Cart.objects.get(cartId=_cartId(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cartId=_cartId(request))

    currentProducts = CartItem.objects.filter(product=product,cart=cart)
    exiting_products_variation = []
    ids = []
    if len(currentProducts)>0:
        for i in currentProducts:
            exiting_products_variation.append(list(i.variation.all()))
            ids.append(i.id)

        if product_variation in exiting_products_variation:
            index = exiting_products_variation.index(product_variation)
            id = ids[index]
            cart_item = CartItem.objects.get(product=product,id=id)
            cart_item.quantity +=1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(product=product,cart=cart,qunatity=1)
            if len(product_variation)>0:
                cart_item.variation.clear()
                for i in product_variation:
                    cart_item.variation.add(i)
            cart_item.save()
    else:
        cart_item = CartItem.objects.create(product=product,cart=cart,quantity=1)
        if len(product_variation)>0:
           cart_item.variation.clear()
           for i in product_variation:
               cart_item.variation.add(i)
        cart_item.save()
    return redirect('cart')

def increaseQuantity(request,cart_item_id):
    try:
        cart_item = CartItem.objects.get(id=cart_item_id)
        cart_item.quantity+=1
        cart_item.save()
    except:
        pass
    return redirect('cart')

ecomsite/store/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse
from .models import Product
from Category.models import Category
from Cart.models import CartItem,Cart
from Cart.views import  _cartId
from django.db.models import Q
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator

# Create your views here.
def store(request,category_slug=None):
    products= None
    category = None
    if category_slug != None:
        category = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=category,is_available=True).order_by('id')
        paginator = Paginator(products, 3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products,3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {
        'products':paged_products,
        'product_count':product_count
    }
    return render(request,'store.html',context)


def product_details(request,category_slug,product_slug):
    product = get_object_or_404(Product,slug=product_slug)
    in_cart = CartItem.objects.filter(cart__cartId=_cartId(request),product=product).exists()
    context = {
        'product':product,
        'incart':in_cart
    }
    return render(request,'product_details.html',context)

def search(request):
    if 'q' in request.GET:
        q = request.GET.get('q')
        if q:
            result = Product.objects.order_by('-created_at').filter(Q(description__icontains=q)|Q(product_name__icontains=q))
        context={
            'products':result,
            'product_count':result.count(),
        }
    else:
        context = {'products':None}
    return render(request,'store.html',context)

ecomsite/templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="{% static 'static/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'static/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'static/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'static/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'static/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'static/css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'static/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'static/js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

});
// jquery end
</script>

</head>
<body>

{% include  'includes/nav.html' %}
 {% block  content %}
 {% endblock %}
{% include  'includes/footer.html' %}
</body>
</html>

ecomsite/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cartItems %}
	<h2 class="text-center">Your Shopping Cart is empty</h2>
	<div class="text-center">
		<a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
	</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for item in cartItems %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{MEDIA_URL}}{{item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{item.product.get_url}}" class="title text-dark">{{item.product.product_name}}</a>
				<p class="text-muted small">
					{% if item.variation.all %}
					  {% for i in item.variation.all %}
						{{i.variationChoice | capfirst }}:{{i.variationValue |capfirst}}
					  {% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'subtractfromcart' item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{item.quantity}}">
							<div class="input-group-append">
							<a href="{% url 'increasequantity' item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">${{item.sub_total}}</var>
			<small class="text-muted"> ${{item.product.price}} each </small>
		</div> <!-- price-wrap .// -->
	</td>

	<td class="text-right">
	<a href="{% url 'removeFromCart' item.id %}" class="btn btn-danger"> Remove</a>
	</td>

</tr>
 {% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static 'static/images/misc/payments.png' %}" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

ecomsite/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}

<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src="{% static 'static/images/banners/cover.jpg' %}" class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="{% url 'store' %}" class="btn btn-outline-primary float-right">See all</a>
	<h3 class="section-title">Popular products</h3>
</header><!-- sect-heading -->


<div class="row">
	{% for product in products %}
	<div class="col-md-3">
		<div class="card card-product-grid">
			<a href="{{product.get_url}}" class="img-wrap"> <img src="{{MEDIA_URL}}{{product.images.url}}"> </a>
			<figcaption class="info-wrap">
				<a href="./product-detail.html" class="title">{{product.product_name}}</a>
				<div class="price mt-1">${{product.price}}</div> <!-- price-wrap.// -->
			</figcaption>
		</div>
	</div> <!-- col.// -->
	{% endfor %}
</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->

{% endblock %}

ecomsite/templates/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#"><img src="{{MEDIA_URL}}{{product.images.url}}"></a>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
<form action="{% url 'addToCart' product.id %}" method="POST">

<article class="content-body">

<h2 class="title">{{product.product_name}}</h2>

<div class="mb-3">
	<var class="price h4">${{product.price}}</var>
</div>

<p>{{product.description}}</p>
	{% csrf_token %}
<hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<select name="Color"  class="form-control" required>
			    <option value="" disabled selected>Choose Color</option>
				{% for i in product.productvariation_set.colors %}
					<option value="{{i.variationValue | lower }}">{{i.variationValue | capfirst}}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select name="Size" class="form-control" >
				<option value="" required disabled>Choose Sizes</option>
				{% for i in product.productvariation_set.sizes %}
					<option value="{{i.variationValue | lower }}">{{i.variationValue | capfirst}}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<hr>
 {% if product.stock <= 0 %}
	 <h5 class="text-danger">out of stock</h5>
 {% else %}
	<button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
 {% endif %}
</article> <!-- product-info-aside .// -->
</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>

	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="{% static 'static/images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">24.04.2020 </span>
				<h6 class="mb-1">Mike John </h6>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>
		</div>
	</article>

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

ecomsite/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block  content %}
  <!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">

<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Search result</h2>
	{% else %}
	<h2 class="title-page">Our Store</h2>
	{% endif %}
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">

<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">

				<ul class="list-menu">
					<li><a href="{% url 'store' %}">All</a></li>

				{% for link in links %}
					<li><a href="{{link.get_url}}">{{link.category_name}}  </a></li>
				{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">

				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto"><b> {% if products %} {{product_count}} {% else %} 0 {% endif %}</b> Items found </span>

		</div>
</header><!-- sect-heading -->

<div class="row">
   {% if not products %}
	  <div class="col-12">
		  <div class="text-center">
		  <h4 class="text-center">No products found</h4>
	  </div>
	  </div>
   {% else %}
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap">

				<img src="{{MEDIA_URL}}{{product.images.url}}">

			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">${{product.price}}</span>
					</div> <!-- price-wrap.// -->
				</div>
				<a href="{{ product.get_url }}" class="btn btn-block btn-success">View Details</a>
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor %}
 {% endif %}
</div> <!-- row end.// -->

{% if products.has_other_pages %}
<nav class="mt-4" aria-label="Page navigation sample">
  <ul class="pagination">
	{% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
	{% else %}
	  <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}
    {% for i in products.paginator.page_range %}
	  {% if products.number == i %}
    	<li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
	  {% else %}
	       	<li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
	  {% endif %}
	{% endfor %}
 {% if products.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
 {% else %}
	  <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
  {% endif %}
  </ul>
</nav>
{% endif %}

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}